### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by tim77**

### CODE REVIEW

**Comment by SilverRainZ** [comment]
Hello @tim77, thanks for your translation.

:'( I am very sorry that I did not update the original text to `po/srain.pot` for a long time (and I updated it just now), can you please fetch the newest master and update your translation?
Sorry for the inconvenience and thanks for you contribution again.

**Comment by tim77** [comment]
Sure no prob.

**Comment by SilverRainZ** [comment]
You can add a new line "ru" in `po/LANGS`, then execute `make install-po`, it will merge your current translation to newest original text.

**Comment by tim77** [comment]
Working on it. Many updates here... :)

**Pull request closed without merging**
