### PR TITLE
Add libera.chat IRC network

### PR DESCRIPTION
**Pull request by SilverRainZ**

### CODE REVIEW

**Comment by marlop352** [comment]
@SilverRainZ I'm currently op of the #srain channel on libera, if you want it just say and join the channel so that I can op you and leave for you to register it.

**Comment by SilverRainZ** [comment]
@marlop352  Thank you, I will register channel this weekend.

**Comment by marlop352** [comment]
@SilverRainZ my internet is fairly limited right now (fiber ruptured somewhere yesterday), and Saturday/Sunday I might not even have connection on my phone, it might be better to schedule it to either today or to Monday and onward.

**Comment by SilverRainZ** [comment]
@marlop352  OK, let's meet on Monday.

**Pull request merged**
