### PR TITLE
Adding more pre-defined servers, as per file TODO

### PR DESCRIPTION
**Pull request by gcarreno**
Hey there,

I'm including:

* DALnet
* EFnet
* IRCnet
* Undernet
* Quakenet

Cheers,
Gus

### CODE REVIEW

**Comment by SilverRainZ** [comment]
Thank for you contribuation!
Can you please provide the source of the newly added addresses? (Just in comment, not in code).

**Comment by SilverRainZ** [comment]
I tested these networks, some of them not works well:

- [x] DALnet: OK
- [ ] EFnet:
    - TLS ON: Failed to connect to EFnet(irc.efnet.fr:6697): Peer failed to perform TLS handshake: The TLS connection was non-properly terminated.
    - TLS OFF: seems OK
- [ ] IRCnet
    - TLS ON: Failed to connect to IRCnet(irc.ircnet.com:6697): Peer failed to perform TLS handshake: The TLS connection was non-properly terminated.
    - TLS OFF: seems OK
- [ ] Undernet
    - TLS ON: No response
    - TLS OFF: seems OK
- [ ] Quakenet:
    - TLS ON: No response
    - TLS OFF: seems OK

Since srain will choose 6697 as TLS port by default when no port is given, you should provide the correct TLS port or reomve the line `tls = true`.

**Comment by gcarreno** [comment]
Hey there,

> Can you please provide the source of the newly added addresses? (Just in comment, not in code).

I started with these 2:

* https://en.wikipedia.org/wiki/Internet_Relay_Chat
* https://www.mirc.co.uk/servers.html

Then from the mIRC one I went to their official pages, found the Servers page and copied their listing.
From the Wikipedia one I picked the big ones listed above the "Timeline" paragraph.

In terms of TLS, you are right, I need to fix that. I wasn't sure if any of them had it. I just assumed that if they were operating today, they would have the latest security up. Looks like another case of "Assumptions are the mother of all f*ck ups (tm)" :)

I'll remove TLS from all but DALnet then.

Cheers,
Gus

**Comment by gcarreno** [comment]
> Beside, I think we does not need so many backup addresses because the irc.* domain is usually a load balance of others.

I agree with this and struggled if I would include the full list on each network's site.

I then thought that a list of them with countries would make sense if you want to connect to a server physically near you.

What do you think?

**Comment by gcarreno** [comment]
> IMO, An unencrypted TCP connection is dangerous today, I hope that we can provide TLS port as possible.

This makes much sense.

I remember that some of the servers mentioned SSL near them, so I'll revisit the listings and add the 6697 port explicitly.

I was also thinking about adding 6667 to all the others and turning tls=true on that group.

What do you think?

**Comment by SilverRainZ** [comment]
> I then thought that a list of them with countries would make sense if you want to connect to a server physically near you.

Yes, this make sense, so keep these addresses is also fine.

> I remember that some of the servers mentioned SSL near them, so I'll revisit the listings and add the 6697 port explicitly.

Thanks, please add them.

> I was also thinking about adding 6667 to all the others and turning tls=true on that group.

Why? 6667 is an non-TLS port in IRC protocol, turning on it only cause error.

**Comment by gcarreno** [comment]
> Why? 6667 is an non-TLS port in IRC protocol, turning on it only cause error.

Ahh, ok got it. I'll not do that the. I'll leave it with no port.

I'll do the 2 things you agreed on your last comment and then ping you again.

**Comment by gcarreno** [comment]
All done, ready for your review.

**Comment by SilverRainZ** [comment]
So no one of the remaining server provides TLS port?

**Comment by gcarreno** [comment]
> So no one of the remaining server provides TLS port?

I've gone through all the network's official server pages and these are the ones they mention having SSL/TLS.

So YES :)

**Pull request merged**
